import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "@/_styles/globals.css";
import Sidebar from "@/components/layout/sidebar/Sidebar";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <div className="container h-screen grid grid-cols-[320px_minmax(0,1fr)]">
          <Sidebar />

          {children}
        </div>
      </body>
    </html>
  );
}
